const bcrypt = require("bcryptjs");
const data = {
  users: [
    {
      name: "Quang",
      email: "quangnv.0212@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Vũ",
      email: "quangnv@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "Vũ",
      email: "teoquoc0212@gmail.com",
      password: bcrypt.hashSync("ngulol69"),
      isAdmin: false,
    },
  ],
  albums: [
    {
      name: "ABBEY ROAD",
      artist: "The Beatles",
      year: 1969,
      category: "Rock & Roll",
      color: "Đen",
      format: "Đĩa Than (Vinyl)",
      record: "Apple Records",
      vinylStatus: "EX",
      caseStatus: "OBI",
      country: "Japan",
      code: "EAS-80560",
      image:
        "https://vocrecords.vn/wp-content/uploads/2022/09/the-beatles-abbey-road-front.jpg",
      price: 800000,
      countInStock: 1,
    },
    {
      name: "SPIRITED AWAY SOUNDTRACK ALBUM",
      year: 2001,
      artist: "JOE HISAISHI, STUDIO GHIBLI RECORDS",
      category: "Soundtrack",
      color: "Đen",
      format: "Đĩa Than (Vinyl)",
      record: " Studio Ghibli Records",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "Japan",
      code: "EAS-80560",
      image:
        "https://vocrecords.vn/wp-content/uploads/2021/04/Joe-Hisaishi_Spirited-Away-Soundtrack.jpg",
      price: 1540000,
      countInStock: 0,
    },
    {
      // id: 3,
      // _id: 3,
      name: "STUDIO GHIBLI BOXSET (TRONG)",
      year: 2019,
      artist: "JOE HISAISHI, STUDIO GHIBLI RECORDS",
      category: "Soundtrack",
      color: "Đen",
      format: "1xLP",
      record: " Studio Ghibli Records",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "Japan",
      code: "EAS-80560",
      image:
        "https://vocrecords.vn/wp-content/uploads/2022/12/kiotviet_d54bf41797b81d1ade9dc3fc73fc404d.jpg",
      price: 1990000,
      countInStock: 0,
    },
    {
      // id: 4,
      // _id: 4,
      name: "WEST SIDE STORY ORIGINAL SOUNDTRACK RECORDING",
      year: 1973,
      artist: "OSCAR PETERSON",
      category: "Jazz",
      color: "Đen",
      format: "Đĩa Than (Vinyl)",
      record: "Verve Records",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "Japan",
      code: "MV 2068",
      image:
        "https://vocrecords.vn/wp-content/uploads/2022/12/kiotviet_d54bf41797b81d1ade9dc3fc73fc404d.jpg",
      price: 1990000,
      countInStock: 0,
    },
    {
      // id: 5,
      // _id: 5,
      name: "COME AWAY WITH ME",
      year: 2022,
      artist: "NORAH JONES",
      category: "Jazz",
      color: "Đen",
      format: "Đĩa Than (Vinyl)",
      record: "Universal",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "EU",
      code: "MV 2068",
      image:
        "https://vocrecords.vn/wp-content/uploads/2021/10/norah-jones-come-away-with-ne-800x800.jpg",
      price: 1010000,
      countInStock: 0,
    },
    {
      // id: 6,
      // _id: 6,
      name: "COME AWAY WITH ME",
      year: 2022,
      artist: "NORAH JONES",
      category: "Jazz",
      color: "Đen",
      format: "1xLP",
      record: "Universal",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "EU",
      code: "MV 2068",
      image:
        "https://vocrecords.vn/wp-content/uploads/2021/10/norah-jones-come-away-with-ne-800x800.jpg",
      price: 1010000,
      countInStock: 15,
    },
    {
      // id: 7,
      // _id: 7,
      name: "ABBEY ROAD",
      artist: "The Beatles",
      year: 1969,
      category: "Rock",
      color: "Đen",
      format: "1xLP",
      record: "Apple Records",
      vinylStatus: "EX",
      caseStatus: "OBI",
      country: "Japan",
      code: "EAS-80560",
      image:
        "https://vocrecords.vn/wp-content/uploads/2022/09/the-beatles-abbey-road-front.jpg",
      price: 800000,
      countInStock: 0,
    },
    {
      // id: 8,
      // _id: 8,
      name: "SPIRITED AWAY SOUNDTRACK ALBUM",
      year: 2001,
      artist: "JOE HISAISHI, STUDIO GHIBLI RECORDS",
      category: "Children's",
      color: "Đen",
      format: "Đĩa Than (Vinyl)",
      record: " Studio Ghibli Records",
      vinylStatus: "Mới",
      caseStatus: "Mới",
      country: "Japan",
      code: "EAS-80560",
      image:
        "https://vocrecords.vn/wp-content/uploads/2021/04/Joe-Hisaishi_Spirited-Away-Soundtrack.jpg",
      price: 1540000,
      countInStock: 0,
    },
  ],
};
module.exports = data;
